data:
    dataset: "CelebA_HQ"
    image_size: 256
    channels: 3
    
model:
    type: "simple"
    in_channels: 3
    out_ch: 3
    ch: 128
    ch_mult: [1, 1, 2, 2, 4, 4]
    num_res_blocks: 2
    attn_resolutions: [16, ]
    dropout: 0.0
    var_type: fixedsmall
    ema_rate: 0.999
    ema: True
    resamp_with_conv: True

diffusion:
    beta_schedule: linear
    num_timesteps: 1000
    beta_start: 0.0001
    beta_end: 0.02

samplingDDIM:
    beta_schedule: linear
    beta_start: 0.0001
    beta_end: 0.02
    DDPM_num_timesteps: 1000 
    sigma : 0.00   # generate random source samples with sigma 0.008 0.006 and 0.005
    t : 500 ###  The maximum time steps for inversion and denoising in DDIM
    stepsize_forward: 10 
    stepsize_backward: 50  


training:
    random_source_img: "./data/training/source"
    target_img: "./data/training/target"
    output_img: "./data/training/output"
    pillar_img: "./data/training/pillar"
    n_epochs: 10
    batch_size : 6
    lr : 0.000004
    classifier_text : "sad"



checkpoints:
    pretrained_diffusion_checkpoint: "./pre_trained/celeba_hq.ckpt"
    finetuned_diffusion_checkpoints: "./data/checkpoints"
    pretrained_classifier_FACEID: ./pre_trained/model_ir_se50.pth
    pretrained_classifier_emonet: ./pre_trained/emonet_5.pth



